export interface Province {
  name: string
  districts: string[]
}

export const VIETNAM_PROVINCES: Province[] = [
  {
    name: 'Hà Nội',
    districts: ['Ba Đình','Hoàn Kiếm','Tây Hồ','Long Biên','Cầu Giấy','Đống Đa','Hai Bà Trưng','Hoàng Mai','Thanh Xuân','Nam Từ Liêm','Bắc Từ Liêm','Hà Đông','Sơn Tây','Đông Anh','Gia Lâm','Sóc Sơn','Mê Linh','Thanh Oai','Thường Tín','Phú Xuyên','Ứng Hòa','Mỹ Đức','Chương Mỹ','Hoài Đức','Quốc Oai','Thạch Thất','Đan Phượng','Phúc Thọ','Ba Vì','Thanh Trì'],
  },
  {
    name: 'Hồ Chí Minh',
    districts: ['Quận 1','Quận 3','Quận 4','Quận 5','Quận 6','Quận 7','Quận 8','Quận 10','Quận 11','Quận 12','Bình Thạnh','Gò Vấp','Phú Nhuận','Tân Bình','Tân Phú','Bình Tân','Thủ Đức','Bình Chánh','Hóc Môn','Củ Chi','Nhà Bè','Cần Giờ'],
  },
  {
    name: 'Đà Nẵng',
    districts: ['Hải Châu','Thanh Khê','Sơn Trà','Ngũ Hành Sơn','Liên Chiểu','Cẩm Lệ','Hòa Vang','Hoàng Sa'],
  },
  {
    name: 'Hải Phòng',
    districts: ['Hồng Bàng','Ngô Quyền','Lê Chân','Hải An','Kiến An','Đồ Sơn','Dương Kinh','An Dương','An Lão','Kiến Thụy','Tiên Lãng','Vĩnh Bảo','Cát Hải','Bạch Long Vĩ'],
  },
  {
    name: 'Cần Thơ',
    districts: ['Ninh Kiều','Bình Thủy','Cái Răng','Ô Môn','Thốt Nốt','Vĩnh Thạnh','Cờ Đỏ','Phong Điền','Thới Lai'],
  },
  {
    name: 'Bình Dương',
    districts: ['Thủ Dầu Một','Bến Cát','Tân Uyên','Dĩ An','Thuận An','Bàu Bàng','Bắc Tân Uyên','Dầu Tiếng','Phú Giáo'],
  },
  {
    name: 'Đồng Nai',
    districts: ['Biên Hòa','Long Khánh','Nhơn Trạch','Long Thành','Trảng Bom','Thống Nhất','Cẩm Mỹ','Vĩnh Cửu','Định Quán','Tân Phú','Xuân Lộc'],
  },
  { name: 'Bắc Ninh', districts: ['Bắc Ninh','Từ Sơn','Tiên Du','Yên Phong','Quế Võ','Thuận Thành','Gia Bình','Lương Tài'] },
  { name: 'Hưng Yên', districts: ['Hưng Yên','Mỹ Hào','Văn Lâm','Văn Giang','Yên Mỹ','Ân Thi','Khoái Châu','Kim Động','Phù Cừ','Tiên Lữ'] },
  { name: 'Vĩnh Phúc', districts: ['Vĩnh Yên','Phúc Yên','Lập Thạch','Tam Dương','Tam Đảo','Bình Xuyên','Mê Linh','Sông Lô','Yên Lạc'] },
  { name: 'Hà Nam', districts: ['Phủ Lý','Duy Tiên','Kim Bảng','Thanh Liêm','Bình Lục','Lý Nhân'] },
  { name: 'Nam Định', districts: ['Nam Định','Mỹ Lộc','Vụ Bản','Ý Yên','Nghĩa Hưng','Nam Trực','Trực Ninh','Xuân Trường','Giao Thủy','Hải Hậu'] },
  { name: 'Thái Bình', districts: ['Thái Bình','Quỳnh Phụ','Hưng Hà','Đông Hưng','Thái Thụy','Tiền Hải','Kiến Xương','Vũ Thư'] },
  { name: 'Hải Dương', districts: ['Hải Dương','Chí Linh','Kinh Môn','Nam Sách','Bình Giang','Cẩm Giàng','Gia Lộc','Ninh Giang','Thanh Miện','Tứ Kỳ'] },
  { name: 'Quảng Ninh', districts: ['Hạ Long','Cẩm Phả','Uông Bí','Móng Cái','Cô Tô','Vân Đồn','Tiên Yên','Đầm Hà','Hải Hà','Bình Liêu','Ba Chẽ','Hoành Bồ'] },
  { name: 'Thanh Hóa', districts: ['Thanh Hóa','Sầm Sơn','Bỉm Sơn','Nghi Sơn','Như Xuân','Như Thanh','Nông Cống','Đông Sơn','Quảng Xương','Thiệu Hóa','Hoằng Hóa','Hậu Lộc','Nga Sơn','Hà Trung','Vĩnh Lộc','Yên Định','Thọ Xuân'] },
  { name: 'Nghệ An', districts: ['Vinh','Cửa Lò','Thái Hòa','Hoàng Mai','Con Cuông','Anh Sơn','Diễn Châu','Đô Lương','Hưng Nguyên','Kỳ Sơn','Nam Đàn','Nghi Lộc','Nghĩa Đàn','Quế Phong','Quỳ Châu','Quỳ Hợp','Quỳnh Lưu','Tân Kỳ','Thanh Chương','Tương Dương','Yên Thành'] },
  { name: 'Quảng Nam', districts: ['Tam Kỳ','Hội An','Điện Bàn','Duy Xuyên','Đại Lộc','Điện Bàn','Thăng Bình','Quế Sơn','Hiệp Đức','Phú Ninh','Bắc Trà My','Nam Trà My','Tiên Phước','Tây Giang','Đông Giang','Nam Giang','Phước Sơn','Núi Thành','Nông Sơn'] },
  { name: 'Khánh Hòa', districts: ['Nha Trang','Cam Ranh','Ninh Hòa','Vạn Ninh','Khánh Vĩnh','Khánh Sơn','Trường Sa'] },
  { name: 'Lâm Đồng', districts: ['Đà Lạt','Bảo Lộc','Đam Rông','Lạc Dương','Lâm Hà','Đơn Dương','Đức Trọng','Di Linh','Bảo Lâm','Đạ Huoai','Đạ Tẻh','Cát Tiên'] },
  { name: 'Bà Rịa - Vũng Tàu', districts: ['Vũng Tàu','Bà Rịa','Phú Mỹ','Xuyên Mộc','Long Điền','Đất Đỏ','Châu Đức','Côn Đảo'] },
  { name: 'Bình Thuận', districts: ['Phan Thiết','La Gi','Tuy Phong','Bắc Bình','Hàm Thuận Bắc','Hàm Thuận Nam','Tánh Linh','Đức Linh','Hàm Tân','Phú Quý'] },
  { name: 'Kiên Giang', districts: ['Rạch Giá','Hà Tiên','Kiên Lương','Hòn Đất','Tân Hiệp','Châu Thành','Giồng Riềng','Gò Quao','An Biên','An Minh','Vĩnh Thuận','Giang Thành','Kiên Hải','U Minh Thượng','Phú Quốc'] },
  { name: 'An Giang', districts: ['Long Xuyên','Châu Đốc','An Phú','Tân Châu','Phú Tân','Châu Phú','Tịnh Biên','Tri Tôn','Châu Thành','Chợ Mới','Thoại Sơn'] },
  { name: 'Tiền Giang', districts: ['Mỹ Tho','Gò Công','Cai Lậy','Cái Bè','Châu Thành','Chợ Gạo','Gò Công Đông','Gò Công Tây','Tân Phú Đông','Tân Phước'] },
  { name: 'Bình Phước', districts: ['Đồng Xoài','Phước Long','Bình Long','Bù Đốp','Bù Gia Mập','Lộc Ninh','Bù Đăng','Chơn Thành','Hớn Quản','Đồng Phú'] },
  { name: 'Tây Ninh', districts: ['Tây Ninh','Hòa Thành','Gò Dầu','Trảng Bàng','Dương Minh Châu','Châu Thành','Bến Cầu','Tân Biên','Tân Châu'] },
  { name: 'Long An', districts: ['Tân An','Kiến Tường','Tân Hưng','Vĩnh Hưng','Mộc Hóa','Tân Thạnh','Thạnh Hóa','Đức Huệ','Đức Hòa','Bến Lức','Thủ Thừa','Tân Trụ','Cần Đước','Cần Giuộc','Châu Thành'] },
  { name: 'Đồng Tháp', districts: ['Cao Lãnh','Sa Đéc','Hồng Ngự','Tân Hồng','Tam Nông','Tháp Mười','Cao Lãnh','Lấp Vò','Lai Vung','Châu Thành'] },
  { name: 'Vĩnh Long', districts: ['Vĩnh Long','Bình Minh','Long Hồ','Mang Thít','Tam Bình','Trà Ôn','Vũng Liêm'] },
  { name: 'Bến Tre', districts: ['Bến Tre','Châu Thành','Chợ Lách','Mỏ Cày Bắc','Mỏ Cày Nam','Giồng Trôm','Bình Đại','Ba Tri','Thạnh Phú'] },
  { name: 'Trà Vinh', districts: ['Trà Vinh','Châu Thành','Càng Long','Cầu Kè','Tiểu Cần','Cầu Ngang','Trà Cú','Duyên Hải'] },
  { name: 'Sóc Trăng', districts: ['Sóc Trăng','Ngã Năm','Vĩnh Châu','Châu Thành','Kế Sách','Mỹ Tú','Cù Lao Dung','Long Phú','Mỹ Xuyên','Thạnh Trị','Trần Đề'] },
  { name: 'Bạc Liêu', districts: ['Bạc Liêu','Hòa Bình','Vĩnh Lợi','Giá Rai','Đông Hải','Phước Long','Hồng Dân'] },
  { name: 'Cà Mau', districts: ['Cà Mau','Thới Bình','U Minh','Trần Văn Thời','Cái Nước','Đầm Dơi','Năm Căn','Ngọc Hiển','Phú Tân'] },
  { name: 'Hậu Giang', districts: ['Vị Thanh','Ngã Bảy','Châu Thành','Châu Thành A','Phụng Hiệp','Vị Thủy','Long Mỹ'] },
  { name: 'Thừa Thiên Huế', districts: ['Huế','Hương Thủy','Hương Trà','A Lưới','Nam Đông','Phong Điền','Quảng Điền','Phú Lộc','Phú Vang'] },
  { name: 'Quảng Bình', districts: ['Đồng Hới','Ba Đồn','Minh Hóa','Tuyên Hóa','Bố Trạch','Quảng Ninh','Lệ Thủy'] },
  { name: 'Quảng Trị', districts: ['Đông Hà','Quảng Trị','Vĩnh Linh','Gio Linh','Cam Lộ','Triệu Phong','Hải Lăng','Đakrông','Hướng Hóa','Cồn Cỏ'] },
  { name: 'Quảng Ngãi', districts: ['Quảng Ngãi','Đức Phổ','Mộ Đức','Tư Nghĩa','Nghĩa Hành','Minh Long','Trà Bồng','Tây Trà','Sơn Tịnh','Sơn Hà','Sơn Tây','Ba Tơ','Bình Sơn','Lý Sơn'] },
  { name: 'Bình Định', districts: ['Quy Nhơn','An Nhơn','Hoài Nhơn','Hoài Ân','Phù Mỹ','Phù Cát','Tây Sơn','Vĩnh Thạnh','An Lão','Vân Canh'] },
  { name: 'Phú Yên', districts: ['Tuy Hòa','Sông Cầu','Đồng Xuân','Tuy An','Sơn Hòa','Sông Hinh','Tây Hòa','Phú Hòa','Đông Hòa','Phú Quý'] },
  { name: 'Ninh Thuận', districts: ['Phan Rang-Tháp Chàm','Ninh Hải','Ninh Phước','Ninh Sơn','Bác Ái','Thuận Bắc','Thuận Nam'] },
  { name: 'Gia Lai', districts: ['Pleiku','An Khê','Ayun Pa','KBang','Đak Đoa','Chư Păh','Ia Grai','Mang Yang','Kông Chro','Đức Cơ','Chư Prông','Chư Sê','Đak Pơ','Ia Pa','Phú Thiện','Chư Pưh'] },
  { name: 'Kon Tum', districts: ['Kon Tum','Đắk Hà','Đắk Tô','Kon Rẫy','Ngọc Hồi','Sa Thầy','Tu Mơ Rông','Ia H\'Drai'] },
  { name: 'Đắk Lắk', districts: ['Buôn Ma Thuột','Buôn Hồ','Ea H\'Leo','Ea Súp','Krông Năng','Krông Búk','Krông Ana','Krông Pắc','Krông Bông','Ea Kar','M\'Đrắk','Cư M\'Gar','Buôn Đôn','Cư Kuin','Lắk'] },
  { name: 'Đắk Nông', districts: ['Gia Nghĩa','Đắk Mil','Krông Nô','Đắk Song','Đắk R\'Lấp','Đắk Glong','Cư Jút','Tuy Đức'] },
  { name: 'Lào Cai', districts: ['Lào Cai','Sa Pa','Bắc Hà','Bảo Thắng','Bảo Yên','Mường Khương','Si Ma Cai','Văn Bàn'] },
  { name: 'Yên Bái', districts: ['Yên Bái','Nghĩa Lộ','Lục Yên','Văn Yên','Mù Cang Chải','Trạm Tấu','Văn Chấn','Yên Bình','Trấn Yên'] },
  { name: 'Sơn La', districts: ['Sơn La','Quỳnh Nhai','Thuận Châu','Mường La','Bắc Yên','Phù Yên','Mộc Châu','Yên Châu','Mai Sơn','Sông Mã','Sốp Cộp','Vân Hồ'] },
  { name: 'Điện Biên', districts: ['Điện Biên Phủ','Mường Lay','Điện Biên','Điện Biên Đông','Mường Ảng','Mường Nhé','Nậm Pồ','Tủa Chùa','Tuần Giáo'] },
  { name: 'Lai Châu', districts: ['Lai Châu','Tam Đường','Mường Tè','Sìn Hồ','Phong Thổ','Than Uyên','Tân Uyên','Nậm Nhùn'] },
  { name: 'Hòa Bình', districts: ['Hòa Bình','Đà Bắc','Cao Phong','Tân Lạc','Mai Châu','Lạc Sơn','Yên Thủy','Kim Bôi','Lương Sơn','Lạc Thủy'] },
  { name: 'Phú Thọ', districts: ['Việt Trì','Phú Thọ','Đoan Hùng','Hạ Hòa','Thanh Ba','Cẩm Khê','Yên Lập','Tam Nông','Lâm Thao','Thanh Sơn','Thanh Thủy','Tân Sơn'] },
  { name: 'Thái Nguyên', districts: ['Thái Nguyên','Sông Công','Phổ Yên','Phú Bình','Đồng Hỷ','Võ Nhai','Định Hóa','Đại Từ','Phú Lương'] },
  { name: 'Tuyên Quang', districts: ['Tuyên Quang','Nà Hang','Chiêm Hóa','Hàm Yên','Yên Sơn','Sơn Dương','Lâm Bình'] },
  { name: 'Bắc Kạn', districts: ['Bắc Kạn','Pác Nặm','Ba Bể','Ngân Sơn','Bạch Thông','Chợ Đồn','Nà Rì','Chợ Mới'] },
  { name: 'Cao Bằng', districts: ['Cao Bằng','Bảo Lâm','Bảo Lạc','Thông Nông','Hà Quảng','Trà Lĩnh','Trùng Khánh','Nguyên Bình','Thạch An','Phục Hòa','Quảng Uyên','Hạ Lang'] },
  { name: 'Lạng Sơn', districts: ['Lạng Sơn','Tràng Định','Bình Gia','Văn Lãng','Cao Lộc','Văn Quan','Bắc Sơn','Hữu Lũng','Chi Lăng','Lộc Bình','Đình Lập'] },
  { name: 'Bắc Giang', districts: ['Bắc Giang','Yên Thế','Tân Yên','Lạng Giang','Lục Nam','Lục Ngạn','Sơn Động','Yên Dũng','Việt Yên','Hiệp Hòa'] },
  { name: 'Hà Giang', districts: ['Hà Giang','Đồng Văn','Mèo Vạc','Yên Minh','Quản Bạ','Vị Xuyên','Bắc Mê','Hoàng Su Phì','Xín Mần','Bắc Quang','Quang Bình'] },
]
